coin/billing/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import DetailView
from coin.billing import views

urlpatterns = patterns(
    '',
    url(r'^invoice/(?P<id>.+)/pdf$', views.invoice_pdf, name="invoice_pdf"),
    url(r'^invoice/(?P<id>.+)$', views.invoice, name="invoice"),
    # url(r'^invoice/(?P<id>.+)/validate$', views.invoice_validate, name="invoice_validate"),

    url('invoice/create_all_members_invoices_for_a_period', views.gen_invoices)
)

coin/members/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import DetailView
from coin.members import views
from coin.members.models import Member


urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'members/registration/login.html'},
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^password_change/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': 'members:password_change_done',
         'template_name': 'members/registration/password_change_form.html'},
        name='password_change'),
    url(r'^password_change_done/$', 'django.contrib.auth.views.password_change_done',
        {'template_name': 'members/registration/password_change_done.html'},
        name='password_change_done'),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'members:password_reset_done',
         'template_name': 'members/registration/password_reset_form.html',
         'email_template_name': 'members/registration/password_reset_email.html',
         'subject_template_name': 'members/registration/password_reset_subject.txt'},
        name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'members/registration/password_reset_done.html',
         'current_app': 'members'},
        name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'members:password_reset_complete',
         'template_name': 'members/registration/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'members/registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^detail/$', views.detail,
        name='detail'),

    url(r'^subscriptions/', views.subscriptions, name='subscriptions'),
    # url(r'^subscription/(?P<id>\d+)', views.subscriptions, name = 'subscription'),

    url(r'^invoices/', views.invoices, name='invoices'),
    url(r'^contact/', views.contact, name='contact'),
)

coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views


import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),
    url(r'^vpn/', include('coin.vpn.urls', namespace='vpn')),

    url(r'^admin/', include(admin.site.urls)),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coin/members/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.forms import PasswordResetForm, ReadOnlyPasswordHashField

from coin.members.models import Member


class MemberCreationForm(forms.ModelForm):

    """
    This form was inspired from django.contrib.auth.forms.UserCreationForm
    and adapted to coin specificities
    """
    username = forms.RegexField(required=False,
                                label="Nom d'utilisateur", max_length=30, regex=r"^[\w.@+-]+$",
                                help_text="Laisser vide pour le générer automatiquement à partir du "
                                "nom d'usage, nom et prénom, ou nom de l'organisme")
    password = forms.CharField(
        required=False, label='Mot de passe', widget=forms.PasswordInput,
        help_text="Laisser vide et envoyer un mail de bienvenue pour que "
        "l'utilisateur choisisse son mot de passe lui-même")

    class Meta:
        model = Member
        fields = '__all__'

    def save(self, commit=True):
        """
        Save member, then set his password
        """
        member = super(MemberCreationForm, self).save(commit=False)
        member.set_password(self.cleaned_data["password"])
        if commit:
            member.member()
        return member


class MemberChangeForm(forms.ModelForm):

    """
    This form was inspired from django.contrib.auth.forms.UserChangeForm
    and adapted to coin specificities
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Member
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(MemberChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

    def clean_username(self):
        # idem clean_password
        return self.initial["username"]


class MemberPasswordResetForm(PasswordResetForm):
    pass

coin/members/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.conf import settings


@login_required
def index(request):
    has_isp_feed = 'isp' in [k for k, _, _ in settings.FEEDS]
    return render_to_response('members/index.html',
                              {'has_isp_feed': has_isp_feed},
                              context_instance=RequestContext(request))


@login_required
def detail(request):
    membership_info_url = settings.MEMBER_MEMBERSHIP_INFO_URL
    return render_to_response('members/detail.html',
                              {'membership_info_url': membership_info_url},
                              context_instance=RequestContext(request))


@login_required
def subscriptions(request):
    subscriptions = request.user.get_active_subscriptions()
    old_subscriptions = request.user.get_inactive_subscriptions()

    return render_to_response('members/subscriptions.html',
                              {'subscriptions': subscriptions,
                               'old_subscriptions': old_subscriptions},
                              context_instance=RequestContext(request))


@login_required
def invoices(request):
    invoices = request.user.invoices.filter(validated=True).order_by('-date')

    return render_to_response('members/invoices.html',
                              {'invoices': invoices},
                              context_instance=RequestContext(request))


@login_required
def contact(request):
    return render_to_response('members/contact.html',
                              context_instance=RequestContext(request))

coin/members/templates/members/contact.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2>Contact / Support</h2>
        <div class="panel">
            <h3>Courriel</h3>
            <p>
              <a href="mailto:{{ branding.email }}">{{ branding.email }}</a> (questions générales)<br />
              <a href="mailto:{{ branding.administrative_email }}">{{ branding.administrative_email }}</a> (questions administratives)<br />
              <a href="mailto:{{ branding.support_email }}">{{ branding.support_email }}</a> (support technique)
            </p>
            {% if branding.lists_url %}
            <h3>Listes de discussion</h3>
            <p>Gérer ses abonnements aux listes de discussion et diffusion : <a href="{{ branding.lists_url }}">{{ branding.lists_url }}</a></p>
            {% endif %}
            <h3>IRC</h3>
            <p><a href="{{ branding.chatroom_set.first.url }}">{{ branding.main_chat_verbose }}</a></p>
        </div>
    </div>
</div>
{% endblock %}

coin/members/templates/members/detail.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2>Mes informations personnelles</h2>
    </div>
</div>
<div class="row">
    <div class="large-6 columns">
        <div class="panel">
            <h3>Me joindre</h3>
            <table class="full-width">
                <tr>
                  {% if user.type == 'natural_person' %}
                    <td class="center"><span class="label">Prénom - Nom</span></td>
                    <td>{{user.first_name}} {{user.last_name}}
                      {% if user.nickname %}
                      ({{ user.nickname }})
                      {% endif %}
                    </td>
                  {% else %}
                    <td class="center"><span class="label">Nom de la structure</span></td>
                    <td>{{ user.organization_name }}</td>
                  {% endif %}
                </tr>
                <tr>
                    <td class="center"><span class="label">Adresse</span></td>
                    <td>{{user.address}}<br />{{user.postal_code}} {{user.city}}</td>
                </tr>
                <tr>
                    <td class="center"><span class="label">Email</span></td>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <td class="center"><span class="label">Téléphone fixe</span></td>
                    <td>{{user.home_phone_number}}</td>
                </tr>
                <tr>
                    <td class="center"><span class="label">Téléphone mobile</span></td>
                    <td>{{user.mobile_phone_number}}</td>
                </tr>
            </table>
        </div>
    </div>

    <div class="large-6 columns">
        <div class="panel">
            <h3>Je suis membre de l'association {{ branding.shortname|capfirst }}</h3>
            <p>et ma cotisation est :
                {% if user.is_paid_up %}
                    <span class="label success">à jour !</span>
                {% else %}
                    <span class="label alert">non à jour !</span>
                {% endif %}
            </p>
            <p>Date de fin de cotisation : {{ user.end_date_of_membership }}</p>

            <a href="{{ membership_info_url }}" target="_blank" class="button small radius expand"><i class="fa fa-heart"></i>
 Renouveler ma cotisation</a>
        </div>
        <!--<div class="pa nel">
            <h3>Infos additionnelles</h3>
            <span class="label">Clé ssh</span> coin.pub
        </div>-->
    </div>

</div>
<div class="row">
    <div class="large-12 columns">
        <p>Pour modifier vos informations personnelles et vos coordonnées, veuillez en faire la demande par email à <a href="mailto:{{ branding.administrative_email }}">{{ branding.administrative_email }}</a></p>
    </div>
</div>

{% endblock %}

coin/members/templates/members/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2>Tableau de bord</h2>
    </div>
</div>

<div class="row">
    <div class="large-6 columns">
        <h3>Alertes</h3>
        <div class="panel">Ici les news de santé des serveurs, etc.</div>
    </div>
    <div class="large-6 columns">
        <h3>Stats</h3>
        <div class="panel">Use MOAR bandwidth !</div>
    </div>
    {% if has_isp_feed %}
    <div class="large-6 columns">
        <h3>News {{ branding.shortname|capfirst }}</h3>
        <div class="panel" id="feed_isp"><i class="fa fa-spinner fa-spin"></i>
 Chargement en cours</div>
    </div>
    {% endif %}
    <div class="large-6 columns">
        <h3>News de la FFDN</h3>
        <div class="panel" id="feed_ffdn"><i class="fa fa-spinner fa-spin"></i>
 Chargement en cours</div>
    </div>
</div>

{% endblock %}


{% block js %}
    {{ block.super }}
    <script>
    $(function() {
        {% if has_isp_feed %}
        $.ajax({
            url: "{% url 'feed' feed_name='isp' %}",
        }).done(function(html) {
            $('#feed_isp').html(html);
        }).fail(function() {
            $('#feed_ffdn').html('Erreur lors du chargement du flux');
        });
        {% endif %}
        $.ajax({
            url: "{% url 'feed' feed_name='ffdn' %}",
        }).done(function(html) {
            $('#feed_ffdn').html(html);
        }).fail(function() {
            $('#feed_ffdn').html('Erreur lors du chargement du flux');
        });
    });
    </script>
{% endblock js %}

coin/members/templates/members/invoices.html
{% extends "base.html" %}

{% block content %}
<h2>Mes factures</h2>

<table id="member_invoices" class="full-width">
    <thead>
        <tr>
            <th>Numéro</th>
            <th>Date</th>
            <th>Montant</th>
            <th>Reste à payer</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for invoice in invoices %}
        <tr>
            <td><a href="{% url 'billing:invoice' id=invoice.number %}">{{ invoice.number }}</a></td>
            <td>{{ invoice.date }}</td>
            <td>{{ invoice.amount }}</td>
            <td{% if invoice.amount_remaining_to_pay > 0 %} class="unpaid"{% endif %}>{{ invoice.amount_remaining_to_pay }}</td>
            <td>{% if invoice.is_pdf_exists %}<a href="{% url 'billing:invoice_pdf' id=invoice.number %}"><i class="fa fa-file-pdf-o"></i> PDF</a>{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

coin/members/templates/members/subscriptions.html
{% extends "base.html" %}

{% block content %}
<h2>Mes abonnements</h2>

<table id="member_subscriptions" class="full-width">
    <thead>
        <tr>
            <th width="60">Type</th>
            <th>Offre</th>
            <th>Date de souscription</th>
            <th>Date de résiliation</th>
            <th>Commentaire</th>
            <th>Configuration</th>
        </tr>
    </thead>
    <tbody>
        {% for subscription in subscriptions %}
        <tr>
            <td>{{ subscription.offer.get_configuration_type_display }}</td>
            <td>{{ subscription.offer.name }}</td>
            <td>{{ subscription.subscription_date }}</td>
            <td>{{ subscription.resign_date|default_if_none:"" }}</td>
            <td>{{ subscription.configuration.comment }}</td>
            <td>{% if subscription.configuration and subscription.configuration.url_namespace %}<a class="cfglink" href="{% url subscription.configuration.get_url_namespace|add:":details" id=subscription.configuration.id %}"><i class="fa fa-cog"></i> Configuration</a>{% endif %}</td>
            
        </tr>
        {% endfor %}
        {% for subscription in old_subscriptions %}
        <tr class="inactive">
            <td>{{ subscription.offer.get_configuration_type_display }}</td>
            <td>{{ subscription.offer.name }}</td>
            <td>{{ subscription.subscription_date }}</td>
            <td>{{ subscription.resign_date|default_if_none:"" }}</td>
            <td>{{ subscription.configuration.comment }}</td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!--
     <div class="panel">
         <h3>Stats générales ADSL</h3>
         <a class="button">Voir l'ADSL</a>
     </div>
     <div class="panel">
         <h3>Stats générales VPN</h3>
         <a class="button">Voir le VPN</a>
     </div>-->

{% endblock %}