coin/billing/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import DetailView
from coin.billing import views

urlpatterns = patterns(
    '',
    url(r'^invoice/(?P<id>.+)/pdf$', views.invoice_pdf, name="invoice_pdf"),
    url(r'^invoice/(?P<id>.+)$', views.invoice, name="invoice"),
    # url(r'^invoice/(?P<id>.+)/validate$', views.invoice_validate, name="invoice_validate"),

    url('invoice/create_all_members_invoices_for_a_period', views.gen_invoices)
)

coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views


import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),
    url(r'^vpn/', include('coin.vpn.urls', namespace='vpn')),

    url(r'^admin/', include(admin.site.urls)),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coin/billing/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import random
import uuid
import os
from decimal import Decimal

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from coin.offers.models import OfferSubscription
from coin.members.models import Member
from coin.html2pdf import render_as_pdf
from coin.utils import private_files_storage, start_of_month, end_of_month, \
                       disable_for_loaddata
from coin.isp_database.context_processors import branding

def next_invoice_number():
    """Détermine un numéro de facture aléatoire"""
    return '%s%02i-%i-%i' % (datetime.date.today().year,
                             datetime.date.today().month,
                             random.randrange(100, 999),
                             random.randrange(100, 999))


def invoice_pdf_filename(instance, filename):
    """Nom et chemin du fichier pdf à stocker pour les factures"""
    member_id = instance.member.id if instance.member else 0
    return 'invoices/%d_%s_%s.pdf' % (member_id,
                                      instance.number,
                                      uuid.uuid4())


class Invoice(models.Model):

    INVOICES_STATUS_CHOICES = (
        ('open', 'A payer'),
        ('closed', 'Reglée'),
        ('trouble', 'Litige')
    )

    validated = models.BooleanField(default=False, verbose_name='validée',
                                    help_text='Once validated, a PDF is generated'
                                    ' and the invoice cannot be modified')
    number = models.CharField(max_length=25,
                              default=next_invoice_number,
                              unique=True,
                              verbose_name='numéro')
    status = models.CharField(max_length=50, choices=INVOICES_STATUS_CHOICES,
                              default='open',
                              verbose_name='statut')
    date = models.DateField(
        default=datetime.date.today, null=True, verbose_name='date')
    date_due = models.DateField(
        default=end_of_month,
        null=True,
        verbose_name="date d'échéance de paiement")
    member = models.ForeignKey(Member, null=True, blank=True, default=None,
                               related_name='invoices',
                               verbose_name='membre',
                               on_delete=models.SET_NULL)
    pdf = models.FileField(storage=private_files_storage,
                           upload_to=invoice_pdf_filename,
                           null=True, blank=True,
                           verbose_name='PDF')

    def amount(self):
        """
        Calcul le montant de la facture
        en fonction des éléments de détails
        """
        total = Decimal('0.0')
        for detail in self.details.all():
            total += detail.total()
        return total.quantize(Decimal('0.01'))
    amount.short_description = 'Montant'

    def amount_paid(self):
        """
        Calcul le montant payé de la facture en fonction des éléments
        de paiements
        """
        total = Decimal('0.0')
        for payment in self.payments.all():
            total += payment.amount
        return total.quantize(Decimal('0.01'))
    amount_paid.short_description = 'Montant payé'

    def amount_remaining_to_pay(self):
        """
        Calcul le montant restant à payer
        """
        return self.amount() - self.amount_paid()
    amount_remaining_to_pay.short_description = 'Reste à payer'

    def has_owner(self, username):
        """
        Check if passed username (ex gmajax) is owner of the invoice
        """
        return (self.member and self.member.username == username)

    def generate_pdf(self):
        """
        Make and store a pdf file for the invoice
        """
        context = {"invoice": self}
        context.update(branding(None))
        pdf_file = render_as_pdf('billing/invoice_pdf.html', context)
        self.pdf.save('%s.pdf' % self.number, pdf_file)

    def validate(self):
        """
        Switch invoice to validate mode. This set to False the draft field
        and generate the pdf
        """
        if not self.is_pdf_exists():
            self.validated = True
            self.save()
            self.generate_pdf()

    def is_pdf_exists(self):
        return (self.validated
                and bool(self.pdf)
                and private_files_storage.exists(self.pdf.name))

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('billing:invoice', args=[self.number])

    def __unicode__(self):
        return '#%s %0.2f€ %s' % (self.number, self.amount(), self.date_due)

    class Meta:
        verbose_name = 'facture'


class InvoiceDetail(models.Model):

    label = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=5, decimal_places=2,
                                 verbose_name='montant')
    quantity = models.DecimalField(null=True, verbose_name='quantité',
                                   default=1.0, decimal_places=2, max_digits=4)
    tax = models.DecimalField(null=True, default=0.0, decimal_places=2,
                              max_digits=4, verbose_name='TVA',
                              help_text='en %')
    invoice = models.ForeignKey(Invoice, verbose_name='facture',
                                related_name='details')
    offersubscription = models.ForeignKey(OfferSubscription, null=True,
                                          blank=True, default=None,
                                          verbose_name='abonnement')
    period_from = models.DateField(
        default=start_of_month,
        null=True,
        blank=True,
        verbose_name='début de période',
        help_text='Date de début de période sur laquelle est facturé cet item')
    period_to = models.DateField(
        default=end_of_month,
        null=True,
        blank=True,
        verbose_name='fin de période',
        help_text='Date de fin de période sur laquelle est facturé cet item')

    def __unicode__(self):
        return self.label

    def total(self):
        """Calcul le total"""
        return (self.amount * (self.tax / Decimal('100.0') +
                               Decimal('1.0')) *
                self.quantity).quantize(Decimal('0.01'))

    class Meta:
        verbose_name = 'détail de facture'


class Payment(models.Model):

    PAYMENT_MEAN_CHOICES = (
        ('cash', 'Espèces'),
        ('check', 'Chèque'),
        ('transfer', 'Virement'),
        ('other', 'Autre')
    )

    payment_mean = models.CharField(max_length=100, null=True,
                                    default='transfer',
                                    choices=PAYMENT_MEAN_CHOICES,
                                    verbose_name='moyen de paiement')
    amount = models.DecimalField(max_digits=5, decimal_places=2, null=True,
                                 verbose_name='montant')
    date = models.DateField(default=datetime.date.today)
    invoice = models.ForeignKey(Invoice, verbose_name='facture',
                                related_name='payments')

    def __unicode__(self):
        return 'Paiment de %0.2f€' % self.amount

    class Meta:
        verbose_name = 'paiement'


@receiver(post_save, sender=Payment)
@disable_for_loaddata
def set_invoice_as_paid_if_needed(sender, instance, **kwargs):
    """
    Lorsqu'un paiement est enregistré, vérifie si la facture est alors
    complétement payée. Dans ce cas elle passe en réglée
    """
    if (instance.invoice.amount_paid >= instance.invoice.amount and
            instance.invoice.status == 'open'):
        instance.invoice.status = 'closed'
        instance.invoice.save()

coin/billing/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render, render_to_response
from django.contrib import messages

from sendfile import sendfile

from coin.billing.models import Invoice
from coin.members.models import Member
from coin.html2pdf import render_as_pdf
from coin.billing.create_subscriptions_invoices import create_all_members_invoices_for_a_period
from coin.billing.utils import get_invoice_from_id_or_number, assert_user_can_view_the_invoice


def gen_invoices(request):
    create_all_members_invoices_for_a_period()
    return HttpResponse('blop')


def invoice_pdf(request, id):
    """
    Renvoi une facture générée en format pdf
    id peut être soit la pk d'une facture, soit le numero de facture
    """
    invoice = get_invoice_from_id_or_number(id)

    assert_user_can_view_the_invoice(request, invoice)

    pdf_filename = 'Facture_%s.pdf' % invoice.number

    return sendfile(request, invoice.pdf.path,
                    attachment=True, attachment_filename=pdf_filename)


def invoice(request, id):
    """
    Affiche une facture et son détail
    id peut être soit la pk d'une facture, soit le numero de facture
    """
    invoice = get_invoice_from_id_or_number(id)

    assert_user_can_view_the_invoice(request, invoice)

    return render_to_response('billing/invoice.html', {"invoice": invoice},
                              context_instance=RequestContext(request))

    return response

coin/billing/templates/billing/invoice.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="large-8 columns">
        <h2>Facture N°{{ invoice.number }}</h2>
        <p>Émise le {{ invoice.date }}</p>
    </div>
    <div class="large-4 columns">
        {% if invoice.is_pdf_exists %}<a href="{% url 'billing:invoice_pdf' id=invoice.number %}" target="_blank" class="button expand"><i class="fa fa-file-pdf-o"></i> Télécharger en PDF</a>{% endif %}
    </div>
</div>

<table id="invoice_details" class="invoice-table full-width">
    <thead>
        <tr>
            <th></th>
            <th>Quantité</th>
            <th>PU</th>
            <th class="total">Total TTC</th>
        </tr>
    </thead>
    <tbody>
        {% for detail in invoice.details.all %}
        <tr>
            <td>{{ detail.label }}
                {% if detail.period_from and detail.period_to %}<br/><span class="period">Pour la période du {{ detail.period_from }} au {{ detail.period_to }}{% endif %}</span></td>
            <td>{{ detail.quantity }}</td>
            <td>{{ detail.amount }}€</td>
            <td class="total">{{ detail.total }}€</td>
        </tr>
        {% endfor %}
        <tr class="total">
            <td class="" colspan="3">Total TTC</td>
            <td class="total">{{ invoice.amount }}€</td>
        </tr>
    </tbody>
</table>

<h4>Règlement</h4>

{% if invoice.payments.exists %}
    <table id="invoice_payments" class="invoice-table full-width">
        <thead>
            <tr>
                <th>Type de paiement</th>
                <th>Date</th>
                <th class="total">Montant</th>
            </tr>
        </thead>
        <tbody>
            {% for payment in invoice.payments.all %}
            <tr class="payment">
                <td>{{ payment.get_payment_mean_display }}</td>
                <td>{{ payment.date }}</td>
                <td class="total">-{{ payment.amount }}€</td>
            </tr>
            {% endfor %}
            <tr class="total">
                <td class="" colspan="2">Reste à payer</td>
                <td class="total">{{ invoice.amount_remaining_to_pay }}€</td>
            </tr>
        </tbody>
    </table>
{% endif %}

{% if invoice.amount_remaining_to_pay > 0 %}
    <div id="payment_howto" class="panel">
        <small>
            {% include "billing/payment_howto.html" %}
        </small>
    </div>
{% endif %}

{% endblock %}

coin/billing/templates/billing/invoice_pdf.html
{% load static isptags %}
<html>
	<head>
		<title>Facture N°{{ invoice.number }}</title>

		<style>
		    @page {
		        size: a4 portrait;
		        @frame header_frame {
		            -pdf-frame-content: header_content;
		            left: 50pt; width: 512pt; top: 50pt; height: 70pt;
		        }
		        @frame content_frame {
		            left: 50pt; width: 512pt; top: 120pt; height: 632pt;
		        }
		        @frame footer_frame {
		            -pdf-frame-content: footer_content;
		            left: 50pt; width: 512pt; top: 772pt; height: 30pt;
		        }
		    }
		    body {
		    	font-size: 9pt;
		    }
		    #coordonnees_isp {
		    	font-size:9pt;
		    }
		    #coordonnees_client {
		    	vertical-align: top;
		    }

		    table#details {
		    	width:100%;
		    }
		    th.cell {border:0px;}
		    .cell.result {border:0px; font-weight: bold}
		    .cell { padding:2pt; border:1px solid #DDD; }
		    .cell.label { width:400pt;}
		    .cell.quantity {width:50pt;}
		    .cell.amount {width:50pt;}
		    .cell.total {width:50pt;}

		    .period {color:#888;}

		    #paiements {
		    	background-color:#EEE;
		    	padding:5pt;
		    	font-size:80%;
		    }
		    #page_number {
		    	float:right;
		    }
		</style>

	</head>
<body>
	<div id="header_content">
		<table widht="100%">
			<tr>
				<td><img id="logo" src="{{ branding.logoURL }}" height="70" /></td>
				<td><h1>Facture N°{{ invoice.number }}</h1>
					Le {{ invoice.date }}</td>
			</tr>
		</table>
	</div>
	<div id="footer_content">
		<hr />
		<table widht="100%">
			<tr>
				<td width="50"><img id="logo" src="{{ branding.logoURL }}" height="20" /></td>
				<td>{{ branding.shortname|upper }}, association loi de 1901 à but non lucratif - SIRET : {{ branding.registeredoffice.siret }}</td>
				<td width="20"><pdf:pagenumber>
					/<pdf:pagecount>
				</td>
			</tr>
		</table>
	</div>
	<table>
		<tr>
			<td id="coordonnees_isp">
				<p>
                {% multiline_isp_addr branding %}
				<p>{{ branding.email }}<br/>
				<a href="{{ branding.website }}">{{ branding.website }}</a></p>
			</td>
			<td id="coordonnees_client">
				<strong>Facturé à :</strong><br/>
                {% with member=invoice.member %}
                    {{ member.last_name }} {{ member.first_name }}<br />
                    {% if member.organization_name != "" %}{{ member.organization_name }}<br />{% endif %}
                    {% if member.address %}{{member.address}}<br />{% endif %}
                    {% if member.postal_code and member.city %}
                        {{ member.postal_code }} {{ member.city }}
                    {% endif %}
                {% endwith %}
			</td>
		</tr>
	</table>

	<hr />
	Facture N°{{ invoice.number }}

	<table id="details" repeat="1">
		<thead>
			<tr>
				<th class="cell label"></th>
				<th class="cell quantity">Quantité</th>
				<th class="cell amount">PU</th>
				<th class="cell total">Total</th>
			</tr>
		</thead>
		<tbody>
			{% for detail in invoice.details.all %}
			<tr>
				<td class="cell label">{{ detail.label }}
					{% if detail.period_from and detail.period_to %}<br/><span class="period">Pour la période du {{ detail.period_from }} au {{ detail.period_to }}{% endif %}</span></td>
				<td class="cell quantity">{{ detail.quantity }}</td>
				<td class="cell amount">{{ detail.amount }}€</td>
				<td class="cell total">{{ detail.total }}€</td>
			</tr>
			{% endfor %}
			<tr>
				<td class="cell result"></td>
				<td class="cell result total_ttc" colspan="2">Total TTC</td>
				<td class="cell result invoice_amount">{{ invoice.amount }}€</td>
			</tr>
		</tbody>
	</table>
	<div id="paiements">
        {% include "billing/payment_howto.html" %}
	</div>

</body>
</html>

coin/billing/templates/billing/payment_howto.html
{% load isptags %}

<p><strong>Merci de préférer si possible le paiement par virement</strong></p>

<p>
<strong>Virement</strong><br />
Titulaire du compte : {{ branding.shortname|upper }}<br/>
IBAN : {{ branding.bankinfo.iban|pretty_iban }}<br />

{% if branding.bankinfo.bic %}
    BIC : {{ branding.bankinfo.bic }}<br />
{% endif %}
Merci de faire figurer le code suivant sur votre virement : <strong>#{{ invoice.member.id }}</strong>
<br /><br />
<strong>Chèque</strong><br />
{% with address=branding.registeredoffice %}
Paiement par chèque à l'ordre de "{{ branding.bankinfo.check_order }}" envoyé à l'adresse : {{ branding.name|upper }}, {{ address.extended_address }}, {{ address.street_address }}, {{ address.postal_code }} {{ address.locality }}
{% endwith %}
</p>